[package]
name = "assemble"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "assemble"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

hc_zome_assemble_coordinator = { git = "https://github.com/darksoil-studio/assemble", branch = "main" }
